# Generated by Django 2.1.7 on 2019-05-01 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PartOfFace',
            fields=[
                (
                    'id',
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ('photo_name', models.CharField(max_length=100)),
                ('photo_in_base64', models.TextField()),
                ('rgb_array', models.TextField()),
                ('face_landmarks', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                (
                    'id',
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ('photo_in_base64', models.TextField()),
                ('rgb_array', models.TextField(blank=True, default=None, null=True)),
                (
                    'transparent_pixels',
                    models.TextField(blank=True, default=None, null=True),
                ),
                ('number_of_detected_faces', models.IntegerField()),
                (
                    'face_landmarks',
                    models.TextField(blank=True, default=None, null=True),
                ),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleLip',
            fields=[
                (
                    'partofface_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='blog.PartOfFace',
                    ),
                ),
            ],
            bases=('blog.partofface',),
        ),
        migrations.CreateModel(
            name='ExampleNose',
            fields=[
                (
                    'partofface_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='blog.PartOfFace',
                    ),
                ),
            ],
            bases=('blog.partofface',),
        ),
    ]
