from operator import le, gt

SETTINGS_OF_THE_ENDPOINTS = {
    "lips": {
        "INDEX_OF_THE_LOWEST_LANDMARK_OF_NOSE_TIP": 2,
        "INDEX_OF_THE_HIGHEST_LANDMARK_OF_TOP_LIP": 3,
        "PERCENT_OF_THE_DISTANCE_BETWEEN_THE_LOWEST_LANDMARK_OF_NOSE_TIP_AND_THE_HIGHEST_LANDMARK_OF_TOP_LIP": 0.05,
        "INDEX_OF_THE_LOWEST_LANDMARK_OF_CHIN": 8,
        "INDEX_OF_THE_LOWEST_LANDMARK_OF_BOTTOM_LIP": 3,
        "PERCENT_OF_THE_DISTANCE_BETWEEN_THE_LOWEST_LANDMARK_OF_CHIN_AND_THE_LOWEST_LANDMARK_OF_BOTTOM_LIP": 0.5,
        "OFFSET_FROM_THE_LEFTMOST_POINT_AND_RIGHTMOST_POINT_OF_LIPS": 0.25
    },
    "nose": {
        "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_LEFT_EYEBROW": 4,
        "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_RIGHT_EYEBROW": 0,
        "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_NOSE_TIP": 0,
        "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_TOP_LIP": 0,
        "PERCENT_OF_THE_DISTANCE_BETWEEN_THE_LEFTMOST_LANDMARK_OF_NOSE_TIP_AND_THE_LEFTMOST_LANDMARK_OF_TOP_LIP": 0.55,
        "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_NOSE_TIP": 4,
        "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_THE_TOP_LIP": 6,
        "PERCENT_OF_THE_DISTANCE_BETWEEN_THE_RIGHTMOST_LANDMARK_OF_NOSE_TIP_AND_THE_RIGHTMOST_LANDMARK_OF_TOP_LIP":0.55,
        "OFFSET_FROM_THE_LINE_BETWEEN_NOSE_AND_LIPS" : 0.4,
        "OFFSET_FROM_EYEBROWS": 0.07,
        "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_LEFT_EYE": 3,
        "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_RIGHT_EYE": 0,
        "OFFSET_FROM_THE_ENDPOINTS_OF_EYES": 0.2
    }
}

TYPES_OF_ENDPOINTS = {
    "LEFT": {"INDEX_OF_A_COORDINATE": 0, "COMPARSION_OPERATOR": le},
    "RIGHT": {"INDEX_OF_A_COORDINATE": 0, "COMPARSION_OPERATOR": gt},
    "TOP": {"INDEX_OF_A_COORDINATE": 1, "COMPARSION_OPERATOR": le},
    "BOTTOM": {"INDEX_OF_A_COORDINATE": 1, "COMPARSION_OPERATOR": gt}
}
