from operator import gt, le

SETTINGS_OF_THE_ENDPOINTS_OF_LIPS = {
    "INDEX_OF_THE_LOWEST_LANDMARK_OF_THE_NOSE_TIP": 2,
    "INDEX_OF_THE_HIGHEST_LANDMARK_OF_THE_TOP_LIP": 3,
    # Percent of the distance between the lowest landmark of the nose tip
    # and the highest landmark of the top lip
    "DISTANCE_BETWEEN_THE_NOSE_TIP_AND_THE_TOP_LIP": 0.05,
    "INDEX_OF_THE_LOWEST_LANDMARK_OF_THE_CHIN": 8,
    "INDEX_OF_THE_LOWEST_LANDMARK_OF_THE_BOTTOM_LIP": 3,
    # Percent of the distance between the lowest landmark of the chin
    # and the lowest landmark of the bottom lip
    "DISTANCE_BETWEEN_THE_CHIN_AND_THE_BOTTOM_LIP": 0.5,
    "OFFSET_FROM_THE_LEFTMOST_POINT_AND_THE_RIGHTMOST_POINT_OF_THE_LIPS": 0.25,
}

SETTINGS_OF_THE_ENDPOINTS_OF_A_NOSE = {
    "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_THE_LEFT_EYEBROW": 4,
    "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_THE_RIGHT_EYEBROW": 0,
    "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_THE_NOSE_TIP": 0,
    "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_THE_TOP_LIP": 0,
    # Percent of the distance between the leftmost or rightmost landmark of the nose tip
    # and the leftmost or rightmost landmark of the top lip
    "DISTANCE_BETWEEN_THE_NOSE_TIP_AND_THE_TOP_LIP": 0.4875,
    "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_THE_NOSE_TIP": 4,
    "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_THE_TOP_LIP": 6,
    "OFFSET_FROM_THE_LINE_BETWEEN_THE_NOSE_AND_THE_LIPS": 0.3375,
    "OFFSET_FROM_THE_EYEBROWS": 0.07,
    "INDEX_OF_THE_RIGHTMOST_LANDMARK_OF_THE_LEFT_EYE": 3,
    "INDEX_OF_THE_LEFTMOST_LANDMARK_OF_THE_RIGHT_EYE": 0,
    "OFFSET_FROM_THE_ENDPOINTS_OF_THE_EYES": 0.2,
}

TYPES_OF_ENDPOINTS = {
    "LEFT": {"INDEX_OF_A_COORDINATE": 0, "COMPARSION_OPERATOR": le},
    "RIGHT": {"INDEX_OF_A_COORDINATE": 0, "COMPARSION_OPERATOR": gt},
    "TOP": {"INDEX_OF_A_COORDINATE": 1, "COMPARSION_OPERATOR": le},
    "BOTTOM": {"INDEX_OF_A_COORDINATE": 1, "COMPARSION_OPERATOR": gt},
}

MODE_OF_THE_LEFTMOST_POINT = "LEFT"
MODE_OF_THE_RIGHTMOST_POINT = "RIGHT"
